name: Build and Push to Artifactory

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.2.0'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: List the file
      run: ls -al build
